# Numpy

In [1]:
# NumPy (Numerical Python) হলো একটি শক্তিশালী Python লাইব্রেরি যা মূলত বহু-মাত্রিক অ্যারে (multi-dimensional array) এবং গাণিতিক গণনার (numerical computation) জন্য ব্যবহৃত হয়।

In [2]:
import numpy as np


In [3]:
#create array

# 1 dimension array
arr1 = np.array([1, 2, 3, 4])
print(arr1)
# 2 dimension array( like matrix)
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[1 2 3 4]
[[1 2]
 [3 4]]


In [4]:
# Checking Array Properties

arr1.shape     # Shape (e.g., (4,))
arr1.ndim      # Number of dimensions (e.g., 1)
arr1.dtype     # Data type (e.g., int32)
arr1.size      # Total number of elements



4

In [5]:
# Array Operations

arr1 + 2        # Adds 2 to each element
arr1 * 3        # Multiplies each element by 3
arr1 - 1        # Subtracts 1 from each element
arr1 / 2        # Divides each element by 2

# Array-to-array operations
arr1 + arr1     # Adds elements from both arrays


array([2, 4, 6, 8])

In [6]:
# Common NumPy Functions

np.zeros((2, 3))       # 2x3 array filled with zeros
np.ones((3, 3))        # 3x3 array filled with ones
np.eye(4)              # 4x4 identity matrix
np.arange(0, 10, 2)    # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)   # 5 values between 0 and 1 (inclusive)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
#  Basic Statistical Functions

arr1.sum()         # Sum of all elements
arr1.mean()        # Average value
arr1.max()         # Maximum value
arr1.min()         # Minimum value
arr1.std()         # Standard deviation



1.118033988749895

In [8]:
# ndexing and Slicing

arr1[0]        # First element
arr1[-1]       # Last element
arr1[1:3]      # Elements from index 1 to 2


array([2, 3])

In [9]:
# Multi-dimensional Indexing

arr2 = np.array([[1, 2], [3, 4]])

arr2[0, 1]     # First row, second column = 2
arr2[1]        # Second row = [3, 4]


array([3, 4])

In [10]:
# Reshaping and Transposing

a = np.array([[1, 2, 3], [4, 5, 6]])

a.reshape(3, 2)       # Reshape to 3x2
a.T                  # Transpose (rows become columns)



array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
# Concatenation and Splitting

np.concatenate([arr1, arr1])    # Join arrays
np.split(arr1, 2)               # Split into two parts


[array([1, 2]), array([3, 4])]

In [12]:
# Conditional Filtering

arr1[arr1 > 2]     # Filter elements greater than 2


array([3, 4])

In [13]:
# Generating Random Data

np.random.rand(2, 2)        # 2x2 random floats in [0, 1)
np.random.randint(1, 10, 5) # Five random integers between 1 and 9


array([7, 9, 4, 8, 4])